GAME_WIDTH = 1600
GAME_HEIGHT = 900
GAME_TITLE = "Space Invaders"
GAME_BACKGROUNDCOLOR = (0, 0, 0)

# 1: MENU
# 2: DIFICULDADES
# 3: RANKING
# 4: JOGO
# 5: SAIR
GAME_SCREEN = 1

# 0: FÁCIL
# 1: MÉDIO
# 2: DIFÍCIL
# 3: INSANO
GAME_DIFFICULTY = 1